apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon
spec:
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: quay.io/ltsai/rh-mlops-workshop-model:lr
          imagePullPolicy: Always
          name: classifier-1
          livenessProbe:            
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP        
    - metadata:
        labels:
          version: v2
      spec:
        containers:
        - image: quay.io/ltsai/rh-mlops-workshop-model:xgboost
          imagePullPolicy: Always
          name: classifier-2
          livenessProbe:            
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
          readinessProbe:            
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
    graph:
      name: random-ab-test
      implementation: RANDOM_ABTEST
      parameters:
      - name: ratioA
        value: '0.5'
        type: FLOAT
      children:
      - endpoint:
          type: REST
        name: classifier-1
        type: MODEL
      - endpoint:
          type: REST
        name: classifier-2
        type: MODEL        
    name: pred1
    replicas: 1
    annotations:
      predictor_version: v1
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: seldon
spec:
  to:
    kind: Service
    name: seldon-pred1
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None